services:
  - type: web
    name: passman-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGOURL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 3000
